logging.level.com.api.films=DEBUG
spring.output.ansi.enabled=ALWAYS

#Porta que está rodando o projeto
server.port=3000
#Configuração do  caminho para o banco de dados usando PostgreSQL
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/filmesdb
spring.datasource.username=postgres
spring.datasource.password=18263269

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Para ver os logs